### ISSUE TITLE
[BUG] Turret stabilizer does not actually stabilize

### ISSUE THREAD

**Issue by PolySteam** [ACF-Team/ACF-3#402]
**Short Description**

The visual models seeming to be stabilized is because of interpolation on clientside, it is not actually stabilized. There are a large number of ways to correct this, however adding a gyrotrigger entity would probably be beneficial. You can have it fire the gun after the angles are set.

**Branch and Version**
[Dev](https://github.com/ACF-Team/ACF-3/commit/18e01b460ba4ebab3e4edc8f7191fe1ec9ad9546)

Skip to the end, I physgun the table to stop it from moving, the offset is clearly visible.
https://github.com/ACF-Team/ACF-3/assets/38295124/b3c46777-0ade-48b6-bbda-911872c46f8a

**Comment by LiddulBOFH** [comment]
It'd be easier to just fix the issue, originally I had thought the stabilization was fine since I was checking it with debugoverlay and using the internal rotator entity, but that was also a P2P session; I feel that would be time better spent than making an entity solely to control something which likely already is being controlled by something fully capable of doing that (an E2 or starfall, etc).
Basically, no it's not accounting for angular velocity for anything other than stabilization, which looking back was an error, so it should be easy to add to the calculations before anything else occurs

As of writing I'm not able to do anything since I won't be home for another 30 something hours, but between that and Zomboid modding I'll look at it, and should be relatively simple with what the turret already does

**Comment by yoseij** [comment]
Here's a couple of videos which may help to visualize the problem. Poly wanted me to upload them.

https://github.com/ACF-Team/ACF-3/assets/72367202/9e83ed4b-077d-48a4-ba14-c0e8eba3ed4b

https://github.com/ACF-Team/ACF-3/assets/72367202/003e27c9-10b1-4399-bd73-358683be1010

**Comment by LiddulBOFH** [comment]
Stabilization should be fixed with #18f0df9 on dev, unfortunately the visual aspect is just something that'll still be a problem, and not one I know how to solve since that's a much deeper issue.
I'll close this for now.
